-- Módulo 2 (paso 2.4): galerías de fotos en dos niveles
--   foto_tipo_habitacion → fotos de cada tipo (las usa la landing)
--   foto_habitacion      → fotos propias de una habitación (opcionales; si no tiene, usa las de su tipo)
--
-- Solo se guarda la ruta del archivo (en storage/app/public). Laravel guarda y borra los archivos.
-- Una sola foto principal por galería: índice único parcial (WHERE es_principal).
-- Si se borra el tipo o la habitación, sus fotos se borran con él (ON DELETE CASCADE).
--
-- Deshacer: DROP TABLE foto_habitacion; DROP TABLE foto_tipo_habitacion;

SET client_encoding = 'UTF8';

BEGIN;

CREATE TABLE foto_tipo_habitacion (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_habitacion_id bigint       NOT NULL,
    ruta               varchar(255) NOT NULL,
    orden              smallint     NOT NULL DEFAULT 0,
    es_principal       boolean      NOT NULL DEFAULT false,
    created_at         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_foto_tipo_ruta UNIQUE (ruta),
    CONSTRAINT chk_foto_tipo_orden CHECK (orden >= 0),
    CONSTRAINT fk_foto_tipo_tipo FOREIGN KEY (tipo_habitacion_id)
        REFERENCES tipo_habitacion (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_foto_tipo_principal
    ON foto_tipo_habitacion (tipo_habitacion_id) WHERE es_principal;
CREATE INDEX idx_foto_tipo_orden
    ON foto_tipo_habitacion (tipo_habitacion_id, orden);


CREATE TABLE foto_habitacion (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habitacion_id bigint       NOT NULL,
    ruta          varchar(255) NOT NULL,
    orden         smallint     NOT NULL DEFAULT 0,
    es_principal  boolean      NOT NULL DEFAULT false,
    created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_foto_habitacion_ruta UNIQUE (ruta),
    CONSTRAINT chk_foto_habitacion_orden CHECK (orden >= 0),
    CONSTRAINT fk_foto_habitacion_habitacion FOREIGN KEY (habitacion_id)
        REFERENCES habitacion (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_foto_habitacion_principal
    ON foto_habitacion (habitacion_id) WHERE es_principal;
CREATE INDEX idx_foto_habitacion_orden
    ON foto_habitacion (habitacion_id, orden);

COMMIT;
