-- Fotos del salón de eventos (misma estructura que las otras galerías).
-- Se crea ahora para que la landing ya las lea; la pantalla para subirlas llega en el Módulo 8.
-- Deshacer: DROP TABLE foto_salon_evento;

SET client_encoding = 'UTF8';

BEGIN;

CREATE TABLE foto_salon_evento (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_evento_id bigint       NOT NULL,
    ruta            varchar(255) NOT NULL,
    orden           smallint     NOT NULL DEFAULT 0,
    es_principal    boolean      NOT NULL DEFAULT false,
    created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_foto_salon_ruta UNIQUE (ruta),
    CONSTRAINT chk_foto_salon_orden CHECK (orden >= 0),
    CONSTRAINT fk_foto_salon_salon FOREIGN KEY (salon_evento_id)
        REFERENCES salon_evento (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_foto_salon_principal
    ON foto_salon_evento (salon_evento_id) WHERE es_principal;
CREATE INDEX idx_foto_salon_orden
    ON foto_salon_evento (salon_evento_id, orden);

COMMIT;
